### ISSUE TITLE
on off motion

### ISSUE THREAD

**Issue by toshibochan** [luisiam/homebridge-foscam2#2]
can i turn ON and OFF foscam motion sensor using Siri?

**Comment by luisiam** [comment]
I don't think so. Siri is too stupid at the moment lol. iOS 10 adds support for IP camera. I will see what I can do about that =]

On Mon, Jun 13, 2016 at 8:41 PM -0700, "toshibochan" notifications@github.com wrote:

can i turn ON and OFF foscam motion sensor using Siri?

**Comment by toshibochan** [comment]
thanks luisiam!!!!!
