### ISSUE TITLE
Support for new iOS 10 Camera Characteristics (RTSP)

### ISSUE THREAD

**Issue by leoneleone** [luisiam/homebridge-foscam2#4]
Hello,

I'm trying to get my foscam camera Foscam C1 / Foscam C2 camera to work with HomeKit iOS 10 beta as RTSP camera using the new ServiceTypes and Characteristics in iOS 10.

Please refer to the New HomeKitTyoes.js file here:
https://github.com/pdlove/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js

/**
- Service "Camera Control"
  */

Service.CameraControl = function(displayName, subtype) {
  Service.call(this, displayName, '00000111-0000-1000-8000-0026BB765291', subtype);

  // Required Characteristics
  this.addCharacteristic(Characteristic.On);

  // Optional Characteristics
  this.addOptionalCharacteristic(Characteristic.CurrentHorizontalTiltAngle);
  this.addOptionalCharacteristic(Characteristic.CurrentVerticalTiltAngle);
  this.addOptionalCharacteristic(Characteristic.TargetHorizontalTiltAngle);
  this.addOptionalCharacteristic(Characteristic.TargetVerticalTiltAngle);
  this.addOptionalCharacteristic(Characteristic.NightVision);
  this.addOptionalCharacteristic(Characteristic.OpticalZoom);
  this.addOptionalCharacteristic(Characteristic.DigitalZoom);
  this.addOptionalCharacteristic(Characteristic.ImageRotation);
  this.addOptionalCharacteristic(Characteristic.ImageMirroring);
  this.addOptionalCharacteristic(Characteristic.Name);
};

inherits(Service.CameraControl, Service);

/**
- Service "Camera RTP Stream Management"
  */

Service.CameraRTPStreamManagement = function(displayName, subtype) {
  Service.call(this, displayName, '00000110-0000-1000-8000-0026BB765291', subtype);

  // Required Characteristics
  this.addCharacteristic(Characteristic.SupportedVideoStreamConfiguration);
  this.addCharacteristic(Characteristic.SupportedAudioStreamConfiguration);
  this.addCharacteristic(Characteristic.SupportedRTPConfiguration);
  this.addCharacteristic(Characteristic.SelectedStreamConfiguration);
  this.addCharacteristic(Characteristic.StreamingStatus);
  this.addCharacteristic(Characteristic.SetupEndpoints);

  // Optional Characteristics
  this.addOptionalCharacteristic(Characteristic.Name);
};

inherits(Service.CameraRTPStreamManagement, Service);

**Comment by leoneleone** [comment]
I believe the new characteristics above will add RTSP streams directly into HomeKit and the new iOS 10 home app. That would make this plugin complete. 

I'm hoping someone has the time to add these characteristics to the plugin. Shouldn't be too difficult for someone familiar with the Foscam API 🙂

**Comment by luisiam** [comment]
I will definitely take a look at it after iOS 10 is officially released. I still don't feel comfortable installing the beta on my daily driver =]

**Comment by leoneleone** [comment]
@luisiam
That's fair enough. You will have to wait until KhaosT updates HAP-NodeJS with the new Services and Characteristics as well. 

A few homebridge developers are already trying to figure out the new Camera functionalities in HomeKit. @pdlove is probably the best person who can give you details about how it all works, although we are running into some hiccups. No one knows what the TLV8 format the Camera characteristics have to be in, or what the TLV8 is supposed to look like 🙁

**Comment by pdlove** [comment]
@leoneleone I was out earlier this week and was able to make significant progress on getting the information together. I've got to do homey stuff tonight and tomorrow since I was out of town, but I should be able to post the information I have so far about the process in a few days.

**Comment by leoneleone** [comment]
@pdlove
That would be great man. 
Thanks for all the work 🙂 👍🏼

**Comment by leoneleone** [comment]
@pdlove

Any progress? 
Please post the new info you have if it is useful.

**Comment by luisiam** [comment]
KhaosT has published a plugin which enable RTSP. We can use that together with this plugin for now.
https://github.com/KhaosT/homebridge-camera-ffmpeg

Currently, I am not able to add that into the current plugin since IP camera cannot be bridged due to protocol limitation. A separate plugin is probably needed.
https://github.com/KhaosT/HAP-NodeJS/wiki/IP-Camera

**Comment by luisiam** [comment]
planetbeing also wrote a plugin for foscam live streaming
https://github.com/planetbeing/homebridge-foscam-ng

**Comment by luisiam** [comment]
Since RSTP plugin cannot be bridged. I am working on a new plugin with extra features. Give it a try.
https://github.com/luisiam/homebridge-foscamcamera

You will have to add the accessory in the home app separately. PIN will be the same as the homebridge PIN.
