### ISSUE TITLE
Homebridge does not continue

### ISSUE THREAD

**Issue by abataille** [luisiam/homebridge-foscam2#5]
I have the following problem:
I did the install and everything runs well at my Mac test system.
When I install Homebridge-Foscam2 at the RPi, Homebridge starts up normally, but it hangs later on. No errors in the log.
The sequence is as follows:
...
[9/13/2016, 3:55:30 PM] Loaded plugin: homebridge-foscam2
[9/13/2016, 3:55:30 PM] Registering platform 'homebridge-foscam2.Foscam2'
...
[9/13/2016, 3:55:39 PM] Initializing Foscam2 platform...
... loading additional accessories
[9/13/2016, 3:55:42 PM] [Foscam Eingang] Current state: Armed (Night).
 --> this is correct. but then it hangs and does not continue initializing the remaining accessories.

the config.json is
{
        "platform": "Foscam2",
        "cameras": [{
            "username": "xxxxx",
            "password": "xxxxx",
            "host": "192.168.1.20",
            "port": "88",
            "stay": "13",
            "away": "15",
            "night": "14",
            "path": ""
        }

any idea ?

**Comment by luisiam** [comment]
What plugin have you installed? Technically speaking, as long as the status is retrieved, the plugin is finished working. It should not be the the foscam plugin that cause the problem.

One more thing, can you post the whole `config.json`? It looks like there's a syntax error on the portion you posted. You can check json syntax at jsonlint.com

**Comment by abataille** [comment]
jsonlint did not throw a problem.
I am wondering why it works at a Mac, but unaltered not at an rpi.
I tried with home bridge-foscam v.1 that works quite well (still some errors over time).

{
    "bridge": {
        "name": "Homebridge iMac Dev",
        "username": "CC:22:3D:E3:DE:37",
        "port": 51826,
        "pin": "004-45-155"
    },
    "platforms": [{
        "platform": "LightifyNativePlatform",
        "name": "Lightify Native Platform",
        "ip": "192.168.178.27",
        "interval": 20000
    }, {
        "platform": "Foscam2",
        "cameras": [{
            "username": “***_",
            "password": “**_*",
            "host": "192.168.178.20",
            "port": "88",
            "stay": "13",
            "away": "15",
            "night": "14",
            "path": ""
        }]
    }],
    "accessories": [{
        "accessory": "Suncalc",
        "location": {
            "lat": 52.287158,
            "lng": 10.469477
        },
        "offset": {
            "sunriseEnd": 15,
            "sunsetStart": -15
        },
        "name": "Suncalc"
    }, {
        "accessory": "Daylight",
        "location": {
            "lat": 52.287158,
            "lng": 10.469477
        },
        "name": "Daylight Sensor"
    }, {
        "accessory": "Suny",
        "name": "Suny"
    }]
}

**Comment by luisiam** [comment]
So it worked on your mac before? Mine runs on a RPi and I don't have problem with it. Can you run homebridge with full debug mode and see if it gives you more info?

**Comment by abataille** [comment]
Yep.
I wil try tomorrow removing all other accessories and platforms and try foscam2 alone. Still, is there some way to debug ?

**Comment by luisiam** [comment]
Run homebridge in full debug mode first. It may give you more info

**Comment by abataille** [comment]
I did, no hints.

**Comment by luisiam** [comment]
What model of foscam are you using?

**Comment by abataille** [comment]
Fi9821w

**Comment by luisiam** [comment]
Interesting. I am using the same model as well. Just try removing foscam plugin alone to see if homebridge comes back to live?

**Comment by abataille** [comment]
Without the foscam2 plugin (I removed in earlier) everything works well.

**Comment by luisiam** [comment]
Add some debug logging at https://github.com/luisiam/homebridge-foscam2/blob/master/index.js#L52 and https://github.com/luisiam/homebridge-foscam2/blob/master/index.js#L62 to see if it really finish initialization

**Comment by abataille** [comment]
Great. I will try tomorrow morning, when I have access to the rpi. I will let you now.
Thank you. Have a nice day.

**Comment by toshibochan** [comment]
The config file have to be in /home/pi/.homebridge

**Comment by abataille** [comment]
It is.

**Comment by abataille** [comment]
Hi, 
I made some tests.
At the Mac it still works well and runs thru #52 and #62

At the RPi it also runs thru #52 and #62. but then it hangs.

The log at the mac is:

[2016-09-14 12:45:19] [Suncalc] Initializing Suncalc accessory...
[2016-09-14 12:45:19] [Suncalc] Currently Daytime(4). Sunset is at 19:33:52
[2016-09-14 12:45:19] [Suncalc] Sunset time will be offset by -15 minute(s)
[2016-09-14 12:45:19] [Daylight Sensor] Initializing Daylight accessory...
[2016-09-14 12:45:19] [Foscam Eingang] Current state: Disarmed.
[2016-09-14 12:45:19] [Lightify Native Platform] Starting a lightify lamp device  'Plug Wohn’
… my other platforms

at the RPI it is:
[9/14/2016, 12:44:46 PM] [Suncalc] Sunset time will be offset by -1 minute(s)
[9/14/2016, 12:44:46 PM] [Daylight Sensor] Initializing Daylight accessory…
[9/14/2016, 12:44:49 PM] [Foscam Eingang] Current state: Disarmed.

and here it hangs.

The only difference I can see may be the path for the snapshot. What are the requirements for it?

**Comment by abataille** [comment]
Hi, 
I made some tests.
At the Mac it still works well and runs thru #52 and #62

At the RPi it also runs thru #52 and #62. but then it hangs.

The log at the mac is:

[2016-09-14 12:45:19] [Suncalc] Initializing Suncalc accessory...
[2016-09-14 12:45:19] [Suncalc] Currently Daytime(4). Sunset is at 19:33:52
[2016-09-14 12:45:19] [Suncalc] Sunset time will be offset by -15 minute(s)
[2016-09-14 12:45:19] [Daylight Sensor] Initializing Daylight accessory...
[2016-09-14 12:45:19] [Foscam Eingang] Current state: Disarmed.
[2016-09-14 12:45:19] [Lightify Native Platform] Starting a lightify lamp device  'Plug Wohn’
… my other platforms

at the RPI it is:
[9/14/2016, 12:44:46 PM] [Suncalc] Sunset time will be offset by -1 minute(s)
[9/14/2016, 12:44:46 PM] [Daylight Sensor] Initializing Daylight accessory…
[9/14/2016, 12:44:49 PM] [Foscam Eingang] Current state: Disarmed.

and here it hangs.

The only difference I can see may be the path for the snapshot. What are the requirements for it?

I also got an error even without foscam2 in the config.sy

Wed, 14 Sep 2016 11:47:05 GMT Accessory [Homebridge iMac Dev] Getting value for Characteristic "Security System Current State"
/usr/local/lib/node_modules/homebridge-foscam2/index.js:290
  if (this.cameraInfo[thisCamera.mac].ver == 0) {
                                     ^

TypeError: Cannot read property 'ver' of undefined
    at FoscamPlatform.getCurrentState (/usr/local/lib/node_modules/homebridge-foscam2/index.js:290:38)
    at emitTwo (events.js:87:13)
    at Characteristic.emit (events.js:172:7)
    at Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:120:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:604:20)
    at Array.forEach (native)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:568:8)
    at emitThree (events.js:97:13)
    at HAPServer.emit (events.js:175:7)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:914:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:201:39)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)

**Comment by luisiam** [comment]
Try the path as`/home/pi/` for now.

Not sure about why that error occur when you remove foscam2 from the config. You may also want to delete the cache located at `/home/pi/.homebridge/accessories/cacheAccessories` and completely remove the plugin via the `npm remove` command.

**Comment by abataille** [comment]
I am going to remove it and then reinstall it and also remove the cache.

**Comment by luisiam** [comment]
Double check if everything works before reinstalling it

**Comment by abataille** [comment]
Sure

**Comment by abataille** [comment]
I removed and reinstalled foscam2 . Still the same problem. 
My assumption is that it might be problem with the RPi. Mine is Model B Rev 2.0

**Comment by abataille** [comment]
I removed and reinstalled foscam2 . Still the same problem. 
My assumption is that it might be problem with the RPi. Mine is Model B Rev 2.0

Btw. I noticed where the error /usr/local/lib/node_modules/homebridge-foscam2/index.js:290
  if (this.cameraInfo[thisCamera.mac].ver == 0) {…
came from. It occurs if the camera is not available.

**Comment by luisiam** [comment]
If you remove everything related to the foscam2 plugin, including cache and config, will homebridge work?

**Comment by abataille** [comment]
Yes it works without problem.
It also works when foscam2 is still installed but not included in the config.json

**Comment by luisiam** [comment]
I have no idea then. I run the plugin on RPi as well. No problem at all. Probably you will have to stick with the original foscam plugin for now. There's no much big difference anyways. I will probably overhaul this version after IP camera accessory type is added to homebridge

**Comment by abataille** [comment]
That is ok. I will do some more testing over the weekend and let you know in case I can find anything.

**Comment by toshibochan** [comment]
You " on you user name and password is different!!!!???
            "username": “***_",
            "password": “**_*",

**Comment by toshibochan** [comment]
Your quote ( " ) is  wrong on user name and password

**Comment by toshibochan** [comment]
Copy and paste your config in this site and test
http://www.jslint.com

**Comment by abataille** [comment]
That was corrected earlier. Thank you.

**Comment by toshibochan** [comment]
Work?

**Comment by abataille** [comment]
not yet.
Probably an issue with my RPi

**Comment by toshibochan** [comment]
If other plugins working I don't think is your pi. Erase "path" line and try again

**Comment by abataille** [comment]
Will do later. I am currently reinstalling the foscam stuff at the pi, which will take some time.

**Comment by abataille** [comment]
The problems is a different one and obviously does not belong to Foscam2.
In the config.json are two different platforms defined.
When I have Foscam2 as the only platform, it works fine. The same with the other platform alone.
When both platforms are active, foscam hangs.

**Comment by luisiam** [comment]
Is this the other platform that you are using?
https://github.com/hyun007/homebridge-lightify

I feel like this plugin is incomplete.

**Comment by abataille** [comment]
That platform is definitely not a Lightify implementation. We have our own Lightify implementation. We think that something in our rpi installation is corrupt. Since our entire homebridge runs ok at 2 different macs, we will completely setup the rpi over the weekend.

**Comment by abataille** [comment]
I made a full new installation and it works like charm.Thank you for all your help.
